name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # install NodeJs
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
                node-version: 18

        # install CDK dependencies
        - name: Install CDK dependencies
          working-directory: ./
          run: npm ci

        - name: Deploy CDK stack
          working-directory: ./
          run: npx cdk deploy --require-approval never
          env:
           AWS_ACCESS_KEY_ID: ${{ secrets.BETA_AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: "us-east-1" #the region where you previously booted the CDK